In [42]:
import numpy as np
video_file = open("tulips_yuv444_prog_packed_qcif.yuv","rb")

In [43]:
f = np.zeros((2,2,3),dtype=np.uint8)
px = video_file.read(3)
f[0,0,:] = (px[0],px[1],px[2])

In [44]:
f[0,0]

array([ 54, 123, 118], dtype=uint8)

In [80]:
a = np.random.rand(6,6,3)
a[:,1::2,1:] = a[:,::2,1:]
a[1::2,:,1:] = a[::2,:,1:]
print(a)
print(a[0,0,:])

[[[3.92517718e-01 5.35924406e-01 5.53271828e-01]
  [2.98249220e-02 5.35924406e-01 5.53271828e-01]
  [8.24418002e-01 7.18688177e-01 4.61047211e-01]
  [2.12366354e-01 7.18688177e-01 4.61047211e-01]
  [1.31997047e-01 2.88513389e-01 7.28757902e-01]
  [3.82191667e-02 2.88513389e-01 7.28757902e-01]]

 [[7.52756022e-01 5.35924406e-01 5.53271828e-01]
  [6.38728321e-01 5.35924406e-01 5.53271828e-01]
  [5.74439270e-01 7.18688177e-01 4.61047211e-01]
  [1.21985280e-01 7.18688177e-01 4.61047211e-01]
  [6.90811119e-02 2.88513389e-01 7.28757902e-01]
  [8.49237408e-04 2.88513389e-01 7.28757902e-01]]

 [[8.21534967e-01 2.75392195e-01 3.33603756e-01]
  [4.36918081e-01 2.75392195e-01 3.33603756e-01]
  [7.50658327e-01 1.46867816e-01 8.71208641e-01]
  [4.61758939e-01 1.46867816e-01 8.71208641e-01]
  [6.95786081e-01 9.21370831e-01 9.79645109e-01]
  [7.34165968e-01 9.21370831e-01 9.79645109e-01]]

 [[3.19182723e-01 2.75392195e-01 3.33603756e-01]
  [2.61330291e-01 2.75392195e-01 3.33603756e-01]
  [7.82538218e